---
kind: pipeline
type: kubernetes
name: soteria-ci

trigger:
  event:
    include:
    - pull_request

steps:
- name: build
  image: docker:git
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - sleep 5 # give docker enough time to start
    - git clone --single-branch --branch $DRONE_TARGET_BRANCH $DRONE_REMOTE_URL
    - docker build -t base .
    - cd $DRONE_REPO_NAME && docker build -t target .
    
- name: report-gitea
  image: soterias/gitea-reporter:test
  pull: always
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - gitea-reporter.py pr image-scan base target $DRONE_PULL_REQUEST

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

...