apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-reporter-configmap
  namespace: drone
data:
  drone.conf: |
    GITEA_TOKEN=205cfa30140a00387212db867ca3feb5663358a0
    GITEA_USERNAME=gitea_admin
    GITEA_HOST=MINIKUBE_IP
    GITEA_PORT=30280
    SNYK_TOKEN=e961e524-e720-48f3-a2b1-839c60e729bd
    SONAR_URL=http://MINIKUBE_IP:30281
    SONAR_LOGIN=admin
    SONAR_PASSWORD=password
    SONAR_KEY=gitea_admin:feature2
# S3_BUCKET_NAME=YOUR-S3-BUCKET-NAME

# kubectl rollout restart deployment/drone-runner -n drone
