apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: bf5930d3-2442-4c1b-afc6-2613b40c6e47   # Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: dg_-h4aGmuXIvbo-qlQVypAMFzyn-MVcMwqIQEHXo4M= # Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 5b8ddbc6c8ecf48ba08c32612c1a85e1        # openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: 192.168.64.20:32175 # public ip address where we wanna run drone. `minikube service --url droneserver -n drone`
  DRONE_GITEA_SERVER: http://192.168.64.20:30280 # `minikube service --url gitea-charts-http -n gitea`

  # http://gitea-charts-http.gitea.svc.cluster.local:3000/
